export const FETCH_BOOKS_REQUEST = "FETCH_BOOKS_REQUEST";
export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS";
export const FETCH_BOOKS_FAILURE = "FETCH_BOOKS_FAILURE";
export const SORT_BOOKS_BY_DATE = "SORT_BOOKS_BY_DATE";
export const SORT_BOOKS_BY_AUTHOR = "SORT_BOOKS_BY_AUTHOR";
